[app]
    pexels_api_keys = [7KygQ5mPe95mQGiO0Fds3taAlOZSuwdwsJQ12SeSaGJo6GeVaP70shik]
    pixabay_api_keys = []
    llm_provider="g4f"
    gemini_api_key="AIzaSyC6N1MVe9WmAFjWMNuXjlaLnYa8eO813tY"
    gemini_model_name = "gemini-1.0-pro"
    subtitle_provider = "edge"
    hide_config = false
[whisper]
    model_size="small"
    device="CPU"
    compute_type="int8"
